document.addEventListener("alpine:init", () => {
  Alpine.data("movies", () => ({
    items: [
      {
        id: 1,
        title: "Once Upon a Time in America",
        img: "img/movies/america.svg",
        genre: ["Crime", "Drama", "Gangster"],
        filter: "Crime Drama Gangster",
        imdbScore: 8.4,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Sergio Leone",
        cast: "Robert De Niro, James Woods, Elizabeth McGovern",
      },
      {
        id: 2,
        title: "Anna",
        img: "img/movies/anna.svg",
        genre: ["Action", "Thriller", "Spy"],
        filter: "Action Thriller Spy",
        imdbScore: 6.2,
        type: "Movie",
        ageRating: "R",
        country: "France",
        creator: "Luc Besson",
        cast: "Sasha Luss, Helen Mirren, Luke Evans",
      },
      {
        id: 3,
        title: "Blackout",
        img: "img/movies/blackout.svg",
        genre: ["Action", "Thriller", "Disaster"],
        filter: "Action Thriller Disaster",
        imdbScore: 5.3,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "John Pogue",
        cast: "Josh Duhamel, Abbie Cornish, Omar Benson Miller",
      },
      {
        id: 4,
        title: "Blackphone",
        img: "img/movies/blackphone.svg",
        genre: ["Action", "Crime", "Thriller"],
        filter: "Action Crime Thriller",
        imdbScore: 6.5,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Scott Derrickson",
        cast: "Ethan Hawke, James Ransone, Jeremy Davies",
      },
      {
        id: 5,
        title: "Eternals",
        img: "img/movies/eternals.svg",
        genre: ["Action", "Fantasy", "Adventure"],
        filter: "Action Fantasy Adventure",
        imdbScore: 5.5,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "Chloé Zhao",
        cast: "Gemma Chan, Richard Madden, Kumail Nanjiani",
      },
      {
        id: 6,
        title: "Extraction",
        img: "img/movies/extraction.svg",
        genre: ["Action", "Thriller", "Crime"],
        filter: "Action Thriller Crime",
        imdbScore: 6.7,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Sam Hargrave",
        cast: "Chris Hemsworth, Rudhraksh Jaiswal, Golshifteh Farahani",
      },
      {
        id: 7,
        title: "The Godfather",
        img: "img/movies/godfather.svg",
        genre: ["Crime", "Drama", "Gangster"],
        filter: "Crime Drama Gangster",
        imdbScore: 9.2,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Francis Ford Coppola",
        cast: "Marlon Brando, Al Pacino, James Caan",
      },
      {
        id: 8,
        title: "Hustle",
        img: "img/movies/hustle.svg",
        genre: ["Comedy", "Drama", "Sport"],
        filter: "Comedy Drama Sport",
        imdbScore: 7.3,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "Adam Sandler",
        cast: "Adam Sandler, Queen Latifah, Juan",
      },
      {
        id: 9,
        title: "The Irishman",
        img: "img/movies/irish.svg",
        genre: ["Crime", "Drama"],
        filter: "Crime Drama",
        imdbScore: 8.1,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Martin Scorsese",
        cast: ["Robert De Niro", "Al Pacino", "Joe Pesci"],
      },
      {
        id: 10,
        title: "John Wick",
        img: "img/movies/john.svg",
        genre: ["Action", "Thriller"],
        filter: "Action Thriller",
        imdbScore: 8.1,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Derek Kolstad",
        cast: "Keanu Reeves",
      },
      {
        id: 11,
        title: "Joker",
        img: "img/movies/joker.svg",
        genre: ["Drama", "Thriller", "Psychological"],
        filter: "Drama Thriller Psychological",
        imdbScore: 8.4,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Todd Phillips",
        cast: "Joaquin Phoenix",
      },
      {
        id: 12,
        title: "Jurassic World",
        img: "img/movies/jurassic.svg",
        genre: ["Action", "Adventure", "Sci-Fi"],
        filter: "Action Adventure Sci-Fi",
        imdbScore: 7.0,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "Colin Trevorrow",
        cast: "Chris Pratt",
      },
      {
        id: 13,
        title: "The Matrix",
        img: "img/movies/matrix.svg",
        genre: ["Action", "Sci-Fi", "Cyberpunk"],
        filter: "Action Sci-Fi Cyberpunk",
        imdbScore: 8.7,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "The Wachowskis",
        cast: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
      },
      {
        id: 14,
        title: "Minions",
        img: "img/movies/minions.svg",
        genre: ["Animation", "Comedy", "Adventure"],
        filter: "Animation Comedy Adventure",
        imdbScore: 6.5,
        type: "Movie",
        ageRating: "PG",
        country: "USA",
        creator: "Pierre Coffin, Kyle Balda",
        cast: "The voices of Pierre Coffin, Sandra Bullock",
      },
      {
        id: 15,
        title: "Narvik",
        img: "img/movies/narvik.svg",
        genre: ["War", "Drama", "History"],
        filter: "War  Drama History",
        imdbScore: 6.3,
        type: "Movie",
        ageRating: "PG-13",
        country: "Norway",
        creator: "Erik Skjoldbjærg",
        cast: "Kristoffer Joner, Eric Bana",
      },
      {
        id: 16,
        title: "Prey",
        img: "img/movies/prey.svg",
        genre: ["Sci-Fi", "Action", "Horror"],
        filter: "Sci-Fi Action Horror",
        imdbScore: 6.2,
        type: "Movie",
        ageRating: "R",
        country: "USA",
        creator: "Dan Trachtenberg",
        cast: "Amber Midthunder, Dakota Beavers, Stefania LaVie Owen",
      },
      {
        id: 17,
        title: "Rebecca",
        img: "img/movies/rebecca.svg",
        genre: ["Mystery", "Romance", "Thriller"],
        filter: "Mystery Romance Thriller",
        imdbScore: 7.4,
        type: "Movie",
        ageRating: "PG-13",
        country: "UK",
        creator: "Ben Wheatley",
        cast: "Lily James, Armie Hammer, Kristin Scott Thomas",
      },
      {
        id: 18,
        title: "Resident Evil",
        img: "img/movies/resident.svg",
        genre: ["Action", "Sci-Fi", "Horror"],
        filter: "Action Sci-Fi Horror",
        imdbScore: 6.3,
        type: "Movie",
        ageRating: "R",
        country: "Germany",
        creator: "Paul W. S. Anderson",
        cast: "Milla Jovovich, Alice Braga, Shawn Roberts",
      },
      {
        id: 19,
        title: "Sher Shah",
        img: "img/movies/sheershah.svg",
        genre: ["Action", "Biography", "War"],
        filter: "Action Biography War",
        imdbScore: 8.7,
        type: "Movie",
        ageRating: "A",
        country: "India",
        creator: "Vishnu Vardhan",
        cast: "Sidharth Malhotra, Kiara Advani, Pankaj Tripathi",
      },
      {
        id: 20,
        title: "Sonic the Hedgehog",
        img: "img/movies/sonic.svg",
        genre: ["Action", "Adventure", "Comedy"],
        filter: "Action Adventure Comedy",
        imdbScore: 6.3,
        type: "Movie",
        ageRating: "PG",
        country: "USA",
        creator: "Jeff Fowler",
        cast: "Ben Schwartz (voice), Jim Carrey",
      },
      {
        id: 21,
        title: "Spider-Man: No Way Home",
        img: "img/movies/spider.svg",
        genre: ["Action", "Adventure", "Comedy"],
        filter: "Action Adventure Comedy",
        imdbScore: 8.8,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "Jon Watts",
        cast: "Tom Holland, Zendaya, Benedict Cumberbatch",
      },
      {
        id: 22,
        title: "Doctor Strange in the Multiverse of Madness",
        img: "img/movies/strange.svg",
        genre: ["Action", "Fantasy", "Adventure"],
        filter: "Action Fantasy Adventure",
        imdbScore: 7.4,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "Sam Raimi",
        cast: "Benedict Cumberbatch, Elizabeth Olsen, Benedict Wong",
      },
      {
        id: 23,
        title: "Tenet",
        img: "img/movies/tenet.svg",
        genre: ["Action", "Sci-Fi", "Thriller"],
        filter: "Action Sci-Fi Thriller",
        imdbScore: 7.4,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "Christopher Nolan",
        cast: "John David Washington, Robert Pattinson, Elizabeth Debicki",
      },
      {
        id: 24,
        title: "Venom: Let There Be Carnage",
        img: "img/movies/venom.svg",
        genre: ["Action", "Comedy", "Sci-Fi"],
        filter: "Action Comedy Sci-Fi",
        imdbScore: 6.5,
        type: "Movie",
        ageRating: "PG-13",
        country: "USA",
        creator: "Andy Serkis",
        cast: "Tom Hardy, Woody Harrelson",
      },
    ],
    redirectToDetails(movie) {
      const genreParam = movie.genre
        .map((g) => encodeURIComponent(g))
        .join("&genre=");
      window.location.href = `movie.html?title=${encodeURIComponent(
        movie.title
      )}&genre=${genreParam}&img=${encodeURIComponent(
        movie.img
      )}&imdbScore=${encodeURIComponent(
        movie.imdbScore
      )}&type=${encodeURIComponent(movie.type)}&ageRating=${encodeURIComponent(
        movie.ageRating
      )}&country=${encodeURIComponent(
        movie.country
      )}&creator=${encodeURIComponent(movie.creator)}&cast=${encodeURIComponent(
        movie.cast
      )}`;
    },
  }));
});
